# Generated by Django 4.1.3 on 2024-06-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("aadhar_id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("annual_income", models.IntegerField()),
                ("credit_score", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
