# Generated by Django 4.1.3 on 2024-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crs", "0002_loan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="interest_accrued",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="is_closed",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="principal_balance",
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[("Credit Card", "Credit Card")],
                default="Credit Card",
                max_length=50,
            ),
        ),
    ]
