# Generated by Django 4.1.3 on 2024-07-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crs", "0005_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="emi_schedule",
            field=models.TextField(default="[]"),
        ),
    ]
