# Generated by Django 4.1.3 on 2024-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crs", "0006_loan_emi_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
