# Generated by Django 4.1.3 on 2024-06-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crs", "0007_loan_is_closed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crs.loan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                (
                    "principal_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("apr_accrued", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_due", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crs.loan"
                    ),
                ),
            ],
        ),
    ]
